### ISSUE TITLE
Decide on a licence.

### ISSUE THREAD

**Issue by ehne** [Midataur/mathsender#27]
MathSender currently does not have a licence.

I reckon we should prolly put it under [MIT](https://choosealicense.com/licenses/mit/) or [BSD 3-clause](https://tldrlegal.com/license/bsd-3-clause-license-(revised)#summary).

Both of them:
* grant personal use
* grant modification
* grant distribution
* grant private use
* have limitations on liability and warranty.
* require that any redistribution keeps the licence text `The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.`

BSD 3-clause differs from MIT in that it does not allow other people to use the name of the project or the names of contributors to promote their redistribution `Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.`

**Comment by Midataur** [comment]
Do they allow commercial use? It might be nice to reserve that one.

**Comment by ehne** [comment]
hmm, that is a good point, both licences do allow commercial use..

**Comment by ehne** [comment]
[commons clause](https://commonsclause.com) doesn't allow people to "sell" the software (`Without limiting other conditions in the License, the grant of rights under the License will not include, and the License does not grant to you, the right to Sell the Software.`). but they can sell things that they build on top of it. Commons clause also keeps a lot of the features of "open-source" software, but would mean that our software isn't open-source, instead source-available. Which might be what we're going for.

**Comment by ehne** [comment]
Although, even just keeping commercial use of MathSender to ourselves would technically break the definition of [open-source software](https://en.wikipedia.org/wiki/The_Open_Source_Definition)

**Comment by Midataur** [comment]
Yeah fair point, but no one else is exactly contributing anyway

**Comment by Midataur** [comment]
I guess we're more like public source then?

**Comment by ehne** [comment]
yeah, that is true

**Comment by ehne** [comment]
closed by #35
