### ISSUE TITLE
Student side - latex for existing answer

### ISSUE THREAD

**Issue by Jmang0** [Midataur/mathsender#28]
## Describe the bug
On the STUDENT SIDE, latex doesn't render properly when loading already submitted answers.

## To Reproduce
1. As a student, submit an answer
2. Click 'go back' to return to the questions page
3. Click back on the question you answered

The answer shown has the formatting messed up, for some latex.

## Expected behavior
The previous answer to render properly

## Suggested fix
?

## Screenshots
![Screen Shot 2020-08-24 at 12 18 13 pm (2)](https://user-images.githubusercontent.com/44317236/90997975-4b8dd500-e606-11ea-9d78-c6d201b9a71a.png)
![Screen Shot 2020-08-24 at 12 18 21 pm (2)](https://user-images.githubusercontent.com/44317236/90997960-4761b780-e606-11ea-8ad5-93eeef05d797.png)
![Screen Shot 2020-08-24 at 12 18 26 pm (2)](https://user-images.githubusercontent.com/44317236/90997972-4a5ca800-e606-11ea-9b14-ebdfbc07da7e.png)

## Desktop
 - OS: macOS
 - Browser: Chrome

**Comment by ehne** [comment]
yup, can confirm, this does happen, I will investigate the cause of this issue.

**Comment by Jmang0** [comment]
`\frac` seems to become `rac`
Maybe the `\` is stored, then when it's rendered it sees the backslash and does it's thing

**Comment by Jmang0** [comment]
<img width="731" alt="Screen Shot 2020-08-24 at 6 05 11 pm" src="https://user-images.githubusercontent.com/44317236/91019594-932b5580-e634-11ea-9e9a-a765f9358b45.png">
<img width="449" alt="Screen Shot 2020-08-24 at 6 05 21 pm" src="https://user-images.githubusercontent.com/44317236/91019601-96264600-e634-11ea-8811-7144deeb9efb.png">

**Comment by ehne** [comment]
hmm, from what I can tell, its based of how python handles \f in strings, but also, it seems that it works fine one the teacher page, so I guess have a look at what's different with how questions are loaded on both pages

**Comment by ehne** [comment]
okay, so, it is because \f is part of the **js** valid escape sequences. 

<img width="473" alt="Screen Shot 2020-08-25 at 7 15 38 am" src="https://user-images.githubusercontent.com/7551957/91097360-e50ac480-e6a2-11ea-9883-6659aea0e206.png">

this means that it won't show up in any strings. (neither will the others).

Suggested fix:
escaping all backslashes by adding another one before them [(`\frac` → `\\frac`)](https://codepen.io/coolbezos_420/pen/oNxBrrL)
