### ISSUE TITLE
Identical answer autocorrect not updating student side

### ISSUE THREAD

**Issue by Jmang0** [Midataur/mathsender#30]
## Describe the bug
On Mr Finch's screen, an answer Mr Berecic submitted got autocorrected as correct, it turned green.
It didn't say it was correct on Mr Berecic's screen (student side).

## To Reproduce
1. Create a question.
2. Submit an answer and mark it as correct.
3. Submit an identical answer

Does it correct it on the teacher's side?
Does it correct it on the student's side?

## Suggested fix (optional)
- Check if the sockets are working properly.
- Check if the javascript is updating properly.

## Desktop (please complete the following information):
 - OS: Windows (I think)
 - Browser: Chrome (I think)

**Comment by ehne** [comment]
hmm, this is certainly an interesting bug.

the way answers are autocorrected might change when @Midataur eventually merges #26 which is supposed to refactor the autocorrect function.

if it doesn't change the behaviour of the student view then something is most likely going wrong with the js on the student question view.

**Comment by Jmang0** [comment]
yeah I think he's gonna push it after schools over, we'll test it more then

**Comment by Midataur** [comment]
my personal thought is that this might be related to #28

**Comment by Jmang0** [comment]
I tested this, it works now
