### ISSUE TITLE
Update credits?

### ISSUE THREAD

**Issue by Midataur** [Midataur/mathsender#32]
Jai isn't actually in the credits rn, so we should probably add him. Maybe an about page could work.

Also it might be nice to link the github on the actual website.

**Comment by ehne** [comment]
yeah, or like maybe a link to the [contributors page](https://github.com/Midataur/mathsender/graphs/contributors).

and about linking to the github: 
<img width="291" alt="Screen Shot 2020-08-24 at 1 26 12 pm" src="https://user-images.githubusercontent.com/7551957/91000809-64e64f80-e60d-11ea-9d10-1bd54794618f.png">

**Comment by Midataur** [comment]
Yeah work. A seperate about page might be nice anyway to put other things on but that can com later.

**Comment by ehne** [comment]
yeah totally, a seperate page would be nice, but adding another link to the footer is prolly the swiftest solution.

**Comment by ehne** [comment]
closed by #36
