### ISSUE TITLE
Easier code copying

### ISSUE THREAD

**Issue by Jmang0** [Midataur/mathsender#34]
Instead of having to select the code and right click to copy, just hover on the code and click.

Will need some css for:
- hovering
- after clicked, change text to "Copied"
- changing back to the code afterwards

**Comment by Jmang0** [comment]
This probably isn't a priority but shouldn't be too hard to do.
I can get the functionality working, darcy might want to do some css

**Comment by ehne** [comment]
hmm, I can probably whip this up, I've tried doing copying text stuff before, and its not easy enough to warrant doing it right now, maybe after we've sorted out some of the more glaring `Make it work` issues.

**Comment by Jmang0** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

**Comment by ehne** [comment]
yeah, you need to either have the room code be inside of an input element, because you can only save stuff to the clipboard that is selected by the user (which probably wouldn't be super hard to put that text inside, but also, its kinda yucky). Or you can create a service worker and do it that way, but sw's require https, which currently MathSender does not have.

When I originally made that room code box I was kinda thinking in a similar vein to that of kahoot, where folks just type it in on their own device, because it's short enough to not be a massive hassle. if it were like, 32 characters long, then we might have more of an issue.

**Comment by Jmang0** [comment]
Yeah it's alright as it is, but the teacher will have to copy the code into the webex chat

**Comment by Jmang0** [comment]
also i have to copy the code when i'm testing it lmao

**Comment by ehne** [comment]
hmm, navigator doesn't appear to work on safari/webkit.

```TypeError: undefined is not an object (evaluating 'navigator.clipboard.writeText```

we might have to find another way of copying this to the clipboard

**Comment by Jmang0** [comment]
It says it's [supported](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard) and it worked on my safari.

**Comment by ehne** [comment]
hmm, so, its only supported in the most recent Safari, 13.1, which was shipped with MacOS Catalina, so it might be best to find another solution as a number of people still run older versions of MacOS and won't have the new safari.

<img width="970" alt="Screen Shot 2020-08-25 at 12 09 59 pm" src="https://user-images.githubusercontent.com/7551957/91114717-e8667600-e6cb-11ea-9179-5119bbe0a83e.png">

Possibly we either just do a check to see if the browser supports `Navigator.clipboard` or maybe we make the room code code bit a text selection box thingo with no styling so it looks normal, but can be copied by all browsers?

**Comment by Jmang0** [comment]
The other way like you said is using document.execCommand('copy'), but THAT's [obsolete](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand).
Goddamn web development.

**Comment by ehne** [comment]
hmm, gosh dang it, 

its almost like there might be valid reasons for not wanting you to be able to programatically put stuff in a user's clipboard...

but gosh dang it's very yucky this one., I think we might have to shelve this one for a rainy day...

**Comment by Jmang0** [comment]
Maybe we can just not have the fancy formatting if they are in a browser that doesn't support it - just use what we had before.
Do you know how to check for that?

**Comment by ehne** [comment]
hmm, okay, so I've done a bit of research into alternative solutions, and i've found one that works in every browser I have installed: https://clipboardjs.com/ . we might have to do a bit of fiddling around with the current code, but it should work across modern browsers.

**Comment by Jmang0** [comment]
ok i'll have a go with that
