### ISSUE TITLE
add some mobile css.

### ISSUE THREAD

**Issue by ehne** [Midataur/mathsender#42]
Yeah, basically, the header and some of the text kinda looks yuckyyy on mobile, so I might need to fix it up good.

**Comment by Jmang0** [comment]
Yeah the room code box is currently just a set width which doesn't work very well for mobile.

**Comment by ehne** [comment]
yeah, I reckon im going to try and get it to look good once it gets onto the final width of `.container`.

**Comment by ehne** [comment]
closed by #47
